FROM node:18-alpine3.16

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./
# Install dependencies (npm ci makes sure the exact versions in the lockfile gets installed)
RUN npm install

# RUN npm run build
# ENV NODE_ENV production

EXPOSE 3001

CMD ["npm", "run", "dev"]
