version: "3.9"
services:
  frontend:
    build:
      context: ./app
      dockerfile: dockerfile
    volumes:
      - /app/node_modules
      - ${PWD}/app:/app
    environment:
      # requests will be forwarded to http://<DOCKER_HOST>:<TARGET_PORT>
      # This will be similar to accessing: http://localhost:3001
      - TARGET_PORT=3001
      - CHOKIDAR_USEPOLLING=true
      - VIRTUAL_HOST=frontend.localhost
    ports:
      - "3001:3001"
    container_name: frontend
  nginxold:
    container_name: nginx
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/docker/nginx/html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs
      - /var/docker/nginx/vhost:/etc/nginx/vhost.d
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8000:80"
      - "8001:443"
