import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Center } from '@chakra-ui/react';
import Layout from '../components/Layout';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout>
        
        <main className={styles.main}>
        </main>
      </Layout>
    </div>
  )
}
